### ISSUE TITLE
Fix a bug in the password recovery window

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#258]
Description:
The message in the password recovery window has moved. The email doesn't arrive at the post office.

Steps:
1. go to the page https://easy4learn.com/forget
2. enter your email address and click Send
3. see error

Expected result:
an email is sent to the User to reset their password

![image](https://user-images.githubusercontent.com/70699061/100652897-a303b580-3358-11eb-867d-923ebd62d4e2.png)

**Comment by pavel232** [comment]
done
https://github.com/easably/context-tutor/tree/fix-password-recovery-window

**Comment by alexnpol** [comment]
Дев версия Тьютора https://2mymemory.com/

**Comment by MikeRogovskiy** [comment]
@alexnpol 
1) The message in the password recovery window has moved. Bug still reproducible
2) An email to confirm your account has been sent to your email address

**Comment by alexnpol** [comment]
all messages (notifications) appear at the bottom of the screen. So they were in the center
![image](https://user-images.githubusercontent.com/70699061/101396843-f0de6780-38dc-11eb-9722-ee0e18955b73.png)
![image](https://user-images.githubusercontent.com/70699061/101396902-03f13780-38dd-11eb-9d99-0b40194f06f6.png)

**Comment by alexnpol** [comment]
После чистки кэша баг не повторился
