### ISSUE TITLE
The word card is not centered

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#262]
**Describe the bug**
The word card that should open in the middle of the screen has moved up after clicking on the word.

Decision
Move the word card to the center
Layouts https://www.figma.com/file/78GiMuG6zyNqscyIR0Rk8K/Vocabulary?node-id=23%3A235

**To Reproduce**
1. Go to My vocabularu in Tutor
2. Click on ward
3. See error

**Expected behavior**
the word card should be displayed in the center of ' rhfyf

**Screenshots**
![image](https://user-images.githubusercontent.com/70699061/100716160-5dcb9c00-33c9-11eb-80a7-735b283de409.png)

**Comment by pavel232** [comment]
done
https://github.com/easably/context-tutor/tree/fix-word-card-position

**Comment by alexnpol** [comment]
Дев версия Тьютора https://2mymemory.com/

**Comment by MikeRogovskiy** [comment]
@alexnpol still reproducible 
![123](https://user-images.githubusercontent.com/75259195/101356808-adb6d100-38a9-11eb-8c6f-83f5075bb5b4.png)
![1234](https://user-images.githubusercontent.com/75259195/101356813-b0192b00-38a9-11eb-94a9-cccbfeafa219.png)

**Comment by pavel232** [comment]
Изменения пока еще не загружены в дев, ни по одной ишью

**Comment by alexnpol** [comment]
Загрузили на дев. Все работает отлично
